type RelicRarity =
  | "Starter"
  | "Common"
  | "Uncommon"
  | "Rare"
  | "Shop"
  | "Boss"
  | "Event"
  | "Ironclad"
  | "Silent"
  | "Defect"
  | "Watcher";

interface Relic {
  name: string;
  types: RelicRarity[];
}

const BASIC_RELIC = {
  IRONCLAD: "Burning Blood",
  SILENT: "Ring of Snake",
  DEFECT: "Cracked Core",
  WATCHER: "HolyWater",
};

const ALL_RELICS: Relic[] = [
  { name: "Akabeko", types: ["Common"] },
  { name: "Anchor", types: ["Common"] },
  { name: "Ancient Tea Set", types: ["Common"] },
  { name: "Art of War", types: ["Common"] },
  { name: "Astrolabe", types: ["Boss"] },
  { name: "Bag of Marbles", types: ["Common"] },
  { name: "Bag of Preparation", types: ["Common"] },
  { name: "Bird Faced Urn", types: ["Rare"] },
  { name: "Black Blood", types: ["Boss"] },
  { name: "Black Star", types: ["Boss"] },
  { name: "Blood Vial", types: ["Common"] },
  { name: "Bloody Idol", types: ["Event"] },
  { name: "Blue Candle", types: ["Uncommon"] },
  { name: "Boot", types: ["Common"] },
  { name: "Bottled Flame", types: ["Uncommon"] },
  { name: "Bottled Lightning", types: ["Uncommon"] },
  { name: "Bottled Tornado", types: ["Uncommon"] },
  { name: "Brimstone", types: ["Shop", "Ironclad"] },
  { name: "Bronze Scales", types: ["Common"] },
  { name: "Burning Blood", types: ["Starter", "Ironclad"] },
  { name: "Busted Crown", types: ["Boss"] },
  { name: "Cables", types: ["Uncommon", "Defect"] },
  { name: "Calipers", types: ["Rare"] },
  { name: "Calling Bell", types: ["Boss"] },
  { name: "CaptainsWheel", types: ["Rare"] },
  { name: "Cauldron", types: ["Shop"] },
  { name: "Centennial Puzzle", types: ["Common"] },
  { name: "CeramicFish", types: ["Common"] },
  { name: "Champion Belt", types: ["Rare", "Ironclad"] },
  { name: "Charon's Ashes", types: ["Rare", "Ironclad"] },
  { name: "Chemical X", types: ["Shop"] },
  { name: "CloakClasp", types: ["Rare", "Watcher"] },
  { name: "ClockworkSouvenir", types: ["Shop"] },
  { name: "Coffee Dripper", types: ["Boss"] },
  { name: "Cracked Core", types: ["Starter", "Defect"] },
  { name: "CultistMask", types: ["Event"] },
  { name: "Cursed Key", types: ["Boss"] },
  { name: "Damaru", types: ["Common", "Watcher"] },
  { name: "Darkstone Periapt", types: ["Uncommon"] },
  { name: "DataDisk", types: ["Common", "Defect"] },
  { name: "Dead Branch", types: ["Rare"] },
  //{ name: "Dodecahedron", types: ["Uncommon"] },
  { name: "DollysMirror", types: ["Shop"] },
  { name: "Dream Catcher", types: ["Common"] },
  { name: "Du-Vu Doll", types: ["Rare"] },
  { name: "Ectoplasm", types: ["Boss"] },
  { name: "Emotion Chip", types: ["Rare", "Defect"] },
  { name: "Empty Cage", types: ["Boss"] },
  { name: "Enchiridion", types: ["Event"] },
  { name: "Eternal Feather", types: ["Uncommon"] },
  { name: "FaceOfCleric", types: ["Event"] },
  { name: "FossilizedHelix", types: ["Rare"] },
  { name: "Frozen Egg 2", types: ["Uncommon"] },
  { name: "Frozen Eye", types: ["Shop"] },
  { name: "FrozenCore", types: ["Boss", "Defect"] },
  { name: "Fusion Hammer", types: ["Boss"] },
  { name: "Gambling Chip", types: ["Rare"] },
  { name: "Ginger", types: ["Rare"] },
  { name: "Girya", types: ["Rare"] },
  { name: "Golden Idol", types: ["Event"] },
  { name: "GoldenEye", types: ["Rare", "Watcher"] },
  { name: "Gremlin Horn", types: ["Uncommon"] },
  { name: "GremlinMask", types: ["Event"] },
  { name: "HandDrill", types: ["Rare"] },
  { name: "Happy Flower", types: ["Common"] },
  { name: "HolyWater", types: ["Boss", "Watcher"] },
  { name: "HornCleat", types: ["Uncommon"] },
  { name: "HoveringKite", types: ["Boss", "Silent"] },
  { name: "Ice Cream", types: ["Rare"] },
  { name: "Incense Burner", types: ["Rare"] },
  { name: "InkBottle", types: ["Uncommon"] },
  { name: "Inserter", types: ["Boss", "Defect"] },
  { name: "Juzu Bracelet", types: ["Common"] },
  { name: "Kunai", types: ["Uncommon"] },
  { name: "Lantern", types: ["Common"] },
  { name: "Lee's Waffle", types: ["Shop"] },
  { name: "Letter Opener", types: ["Uncommon"] },
  { name: "Lizard Tail", types: ["Rare"] },
  { name: "Magic Flower", types: ["Rare", "Ironclad"] },
  { name: "Mango", types: ["Rare"] },
  { name: "Mark of Pain", types: ["Boss", "Ironclad"] },
  { name: "Mark of the Bloom", types: ["Event"] },
  { name: "Matryoshka", types: ["Uncommon"] },
  { name: "MawBank", types: ["Common"] },
  { name: "MealTicket", types: ["Common"] },
  { name: "Meat on the Bone", types: ["Uncommon"] },
  { name: "Medical Kit", types: ["Shop"] },
  { name: "Melange", types: ["Shop", "Watcher"] },
  { name: "Membership Card", types: ["Shop"] },
  { name: "Mercury Hourglass", types: ["Uncommon"] },
  { name: "Molten Egg 2", types: ["Uncommon"] },
  { name: "Mummified Hand", types: ["Uncommon"] },
  { name: "MutagenicStrength", types: ["Event"] },
  { name: "Necronomicon", types: ["Event"] },
  { name: "NeowsBlessing", types: ["Event"] },
  { name: "Nilry's Codex", types: ["Event"] },
  { name: "Ninja Scroll", types: ["Uncommon", "Silent"] },
  { name: "Nloth's Gift", types: ["Event"] },
  { name: "NlothsMask", types: ["Event"] },
  { name: "Nuclear Battery", types: ["Boss", "Defect"] },
  { name: "Nunchaku", types: ["Common"] },
  { name: "Odd Mushroom", types: ["Event"] },
  { name: "Oddly Smooth Stone", types: ["Common"] },
  { name: "Old Coin", types: ["Rare"] },
  { name: "Omamori", types: ["Common"] },
  { name: "OrangePellets", types: ["Shop"] },
  { name: "Orichalcum", types: ["Common"] },
  { name: "Ornamental Fan", types: ["Uncommon"] },
  { name: "Orrery", types: ["Shop"] },
  { name: "Pandora's Box", types: ["Boss"] },
  { name: "Pantograph", types: ["Uncommon"] },
  { name: "Paper Crane", types: ["Uncommon", "Silent"] },
  { name: "Paper Frog", types: ["Uncommon", "Ironclad"] },
  { name: "Peace Pipe", types: ["Rare"] },
  { name: "Pear", types: ["Uncommon"] },
  { name: "Pen Nib", types: ["Common"] },
  { name: "Philosopher's Stone", types: ["Boss"] },
  { name: "Pocketwatch", types: ["Rare"] },
  { name: "Potion Belt", types: ["Common"] },
  { name: "Prayer Wheel", types: ["Rare"] },
  { name: "PreservedInsect", types: ["Common"] },
  { name: "PrismaticShard", types: ["Shop"] },
  { name: "PureWater", types: ["Boss", "Watcher"] },
  { name: "Question Card", types: ["Uncommon"] },
  { name: "Red Mask", types: ["Event"] },
  { name: "Red Skull", types: ["Common", "Ironclad"] },
  { name: "Regal Pillow", types: ["Common"] },
  { name: "Ring of the Serpent", types: ["Boss", "Silent"] },
  { name: "Ring of the Snake", types: ["Starter", "Silent"] },
  { name: "Runic Capacitor", types: ["Shop", "Defect"] },
  { name: "Runic Cube", types: ["Boss", "Ironclad"] },
  { name: "Runic Dome", types: ["Boss"] },
  { name: "Runic Pyramid", types: ["Boss"] },
  { name: "SacredBark", types: ["Boss"] },
  { name: "Self Forming Clay", types: ["Uncommon", "Ironclad"] },
  { name: "Shovel", types: ["Rare"] },
  { name: "Shuriken", types: ["Uncommon"] },
  { name: "Singing Bowl", types: ["Uncommon"] },
  { name: "SlaversCollar", types: ["Boss"] },
  { name: "Sling", types: ["Shop"] },
  { name: "Smiling Mask", types: ["Common"] },
  { name: "Snake Skull", types: ["Common", "Silent"] },
  { name: "Snecko Eye", types: ["Boss"] },
  { name: "Sozu", types: ["Boss"] },
  { name: "Spirit Poop", types: ["Event"] },
  { name: "SsserpentHead", types: ["Event"] },
  { name: "StoneCalendar", types: ["Rare"] },
  { name: "Strange Spoon", types: ["Shop"] },
  { name: "Strawberry", types: ["Common"] },
  { name: "StrikeDummy", types: ["Uncommon"] },
  { name: "Sundial", types: ["Uncommon"] },
  { name: "Symbiotic Virus", types: ["Uncommon", "Defect"] },
  { name: "TeardropLocket", types: ["Uncommon", "Watcher"] },
  { name: "The Courier", types: ["Uncommon"] },
  { name: "The Specimen", types: ["Rare", "Silent"] },
  { name: "TheAbacus", types: ["Shop"] },
  { name: "Thread and Needle", types: ["Rare"] },
  { name: "Tingsha", types: ["Rare", "Silent"] },
  { name: "Tiny Chest", types: ["Common"] },
  { name: "Tiny House", types: ["Boss"] },
  { name: "Toolbox", types: ["Shop"] },
  { name: "Torii", types: ["Rare"] },
  { name: "Tough Bandages", types: ["Rare", "Silent"] },
  { name: "Toxic Egg 2", types: ["Uncommon"] },
  { name: "Toy Ornithopter", types: ["Common"] },
  { name: "TungstenRod", types: ["Rare"] },
  { name: "Turnip", types: ["Rare"] },
  { name: "TwistedFunnel", types: ["Shop", "Silent"] },
  { name: "Unceasing Top", types: ["Rare"] },
  { name: "Vajra", types: ["Common"] },
  { name: "Velvet Choker", types: ["Boss"] },
  { name: "VioletLotus", types: ["Boss", "Watcher"] },
  { name: "War Paint", types: ["Common"] },
  { name: "WarpedTongs", types: ["Event"] },
  { name: "Whetstone", types: ["Common"] },
  { name: "White Beast Statue", types: ["Uncommon"] },
  { name: "WingedGreaves", types: ["Rare"] },
  { name: "WristBlade", types: ["Boss", "Silent"] },
  { name: "Yang", types: ["Uncommon"] },
];

export { ALL_RELICS, BASIC_RELIC };
export type { RelicRarity };
